[package]
name = "continuum"
version = "0.1.0"
authors = ["Gil Mendes <gil00mendes@gmail.com>"]

[dependencies]
gfx = "0.16.1"
gfx_core = "0.7.1"
gfx_device_gl = "0.14.1"
piston = "0.32.0"
piston3d-gfx_voxel = "0.18.0"
pistoncore-glutin_window = "0.38.0"
vecmath = "0.3.0"
